# WARNING: DON'T ALTER THIS WITHOUT UNDERSTANDING THE WAY THAT IT IS USED
# AND THE IMPLICATIONS OF CHANGING IT
ADOPTEE_STORIES_CONFIG = {
    'MIN_WIDTH': 600,
    'MIN_HEIGHT': 400,
    'FORMATS': {'JPEG',
                },
    'IMAGE_MAX_SIZE': int(2.5 * 2 ** 20),  # 2.5 megabytes
}
